#!/usr/bin/env python3

FLAGS = ['and',
         'alter table',
         'as',
         'between',
         'create database',
         'create table',
         'create index',
         'create view',
         'delete',
         'drop database',
         'drop index',
         'drop table',
         'exists',
         'group by',
         'having',
         'in',
         'insert into',
         'inner join',
         'left join',
         'right join',
         'full join',
         'like',
         'order by',
         'select',
         'or',
        ]
